[package]
name = "draw_queue"
version = "0.1.0"
description = "Basic draw queue with sorting by minimal updates"
license = "Apache-2.0"
authors = [
"Dzmitry Malyshau <kvarkus@gmail.com>",
]

[lib]
name = "draw_queue"
path = "lib.rs"
