[package]
name = "draw_queue"
version = "0.1.0"
description = "Basic draw queue with sorting by minimal updates"
license = "Apache-2.0"
authors = ["The Gfx-rs Developers"]

[lib]
name = "draw_queue"
path = "lib.rs"
