[package]
name = "gfx_phase"
version = "0.1.2"
description = "Render phase abstraction for gfx-rs"
license = "Apache-2.0"
authors = [
"Dzmitry Malyshau <kvarkus@gmail.com>",
]

[lib]
name = "gfx_phase"
path = "lib.rs"

[dependencies.draw_queue]
path = "../queue"
#version = "*"

[dependencies.gfx]
version = "0.6.*"

[dependencies]
log = "*"
draw_state = "*"
