[package]
name = "gfx_scene"
version = "0.1.0"
description = "Space-aware scene rendering and culling"
license = "Apache-2.0"
authors = [
"Dzmitry Malyshau <kvarkus@gmail.com>",
]

[lib]
name = "gfx_scene"
path = "lib.rs"

[dependencies.gfx_phase]
path = "../phase"
#version = "*"

[dependencies.gfx]
version = "0.6.*"

[dependencies.cgmath]
git = "https://github.com/bjz/cgmath-rs"
#version = "*"
