[package]
name = "gfx_scene"
version = "0.0.1"
description = "Space-aware scene rendering and culling."

[lib]
name = "gfx_scene"
path = "lib.rs"

[dependencies.gfx_phase]
path = "../phase"

[dependencies.gfx]
git = "https://github.com/gfx-rs/gfx-rs"

[dependencies.cgmath]
git = "https://github.com/bjz/cgmath-rs"
