[package]
name = "scene"
version = "0.0.1"
description = "Space-aware scene rendering and culling."

[lib]
name = "scene"
path = "lib.rs"

[dependencies.draw]
path = "../draw"

[dependencies.gfx]
git = "https://github.com/gfx-rs/gfx-rs"

[dependencies.cgmath]
#git = "https://github.com/bjz/cgmath-rs"
path = "../../../cgmath-rs"
