[package]
name = "draw"
version = "0.0.1"
description = "Abstract high-level drawing processors."

[lib]
name = "draw"
path = "lib.rs"

[dependencies.queue]
path = "../queue"

[dependencies.gfx]
git = "https://github.com/gfx-rs/gfx-rs"
